# Generated by Django 4.1.2 on 2022-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutpassRecords',
            fields=[
                ('roll_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'REQUESTED'), (2, 'APPROVED'), (3, 'USED'), (4, 'EXPIRED')])),
            ],
        ),
    ]
